# Generated by Django 6.0.6 on 2026-06-10 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tour Categories',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('highlights', models.TextField(blank=True, null=True)),
                ('tour_type', models.CharField(choices=[('cultural', 'Cultural'), ('adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('spiritual', 'Spiritual'), ('scenic', 'Scenic'), ('photography', 'Photography')], default='cultural', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_hours', models.PositiveIntegerField(blank=True, help_text='For day tours', null=True)),
                ('max_group_size', models.PositiveIntegerField(default=15)),
                ('min_group_size', models.PositiveIntegerField(default=1)),
                ('min_age', models.PositiveIntegerField(default=5)),
                ('destination', models.CharField(max_length=200)),
                ('pickup_point', models.CharField(blank=True, max_length=200)),
                ('dropoff_point', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='USD', max_length=3)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('best_season', models.CharField(choices=[('spring', 'Spring (Mar-May)'), ('summer', 'Summer (Jun-Aug)'), ('autumn', 'Autumn (Sep-Nov)'), ('winter', 'Winter (Dec-Feb)'), ('all', 'All Seasons')], default='all', max_length=20)),
                ('entry_fee_included', models.BooleanField(default=False)),
                ('guide_included', models.BooleanField(default=True)),
                ('transport_included', models.BooleanField(default=False)),
                ('meals_included', models.BooleanField(default=False)),
                ('included', models.TextField(blank=True)),
                ('excluded', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='What to bring, dress code etc')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tour.tourcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_slots', models.PositiveIntegerField()),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='tour.tour')),
            ],
            options={
                'verbose_name_plural': 'Tour Availabilities',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(choices=[('nepali', 'Nepali'), ('english', 'English'), ('hindi', 'Hindi'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('french', 'French'), ('german', 'German')], default='english', max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_tours', models.PositiveIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='guide_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('accommodation', models.CharField(blank=True, max_length=200)),
                ('meals', models.CharField(blank=True, max_length=100)),
                ('places_to_visit', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tour.tour')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
