# Generated by Django 5.2.17 on 2026-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
    ]
