# Generated by Django 5.2.16 on 2026-07-27 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('treks', '0002_trek_ai_review_summary_trek_ai_summary_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null if guest/anonymous user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('up', 'Helpful'), ('down', 'Not Helpful')], max_length=10),
        ),
        migrations.AlterField(
            model_name='retrievedsource',
            name='source_type',
            field=models.CharField(choices=[('trek', 'Trek'), ('review', 'Review'), ('gear', 'Gear'), ('policy', 'Booking_Policy'), ('guide', 'Trek Guide Document')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrekDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of this chunk within the document')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_chunks', to='treks.trek')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['trek', 'chunk_index'],
            },
        ),
    ]
