# Generated by Django 5.2.16 on 2026-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('trek', 'Trek'), ('tour', 'Tour'), ('gear', 'Gear'), ('guide', 'Guide')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('review_count_at_analysis', models.PositiveIntegerField(default=0)),
                ('average_rating_at_analysis', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('review_type', 'object_id')},
            },
        ),
    ]
