# Generated by Django 6.0.6 on 2026-06-10 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('highlight', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('extreme', 'Extreme')], max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('max_altitude', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_group_size', models.PositiveIntegerField(default=12)),
                ('min_age', models.PositiveIntegerField(default=12)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx_files/')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('best_season', models.CharField(choices=[('spring', 'Spring (Mar-May)'), ('summer', 'Summer (Jun-Aug)'), ('autumn', 'Autumn (Sep-Nov)'), ('winter', 'Winter (Dec-Feb)'), ('all', 'All Seasons')], default='autumn', max_length=20)),
                ('tims_required', models.BooleanField(default=True)),
                ('permit_info', models.TextField(blank=True, help_text='Permit details and costs')),
                ('gear_list', models.TextField(blank=True, help_text='Recommended gear for the trek')),
                ('included', models.TextField(blank=True)),
                ('excluded', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treks', to='treks.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrekAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_slots', models.PositiveIntegerField()),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='treks.trek')),
            ],
            options={
                'verbose_name_plural': 'Trek Availabilities',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrekImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trek_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treks.trek')),
            ],
        ),
        migrations.CreateModel(
            name='TrekItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altitude_m', models.PositiveIntegerField(blank=True, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=200)),
                ('meals', models.CharField(blank=True, max_length=100)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='treks.trek')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
