# Generated by Django 6.0.6 on 2026-07-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='ai_review_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trek',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trekimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trekimage',
            name='image',
            field=models.ImageField(upload_to='treks/'),
        ),
    ]
